[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "46e1ee0e3aec15427962a83682616ad69e622b3e"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "cecebd129ee7e466142395a400a8befaeab503a94386435ad3c05a29c7288244"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.aarch64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "f48ad1c7275d5a5ee537e6b3a528b6f5bac156fb"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "463b1d1714245ed7d92043c4292d6c24e6490792b920cbc013b752a1e60338ab"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.aarch64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "72d9e64f546cd3caa4498b3b486a1ba081424628"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "8028dec604598547de9cba64e6e1cf97e53ad7746dc8b4a1aa2ffdf65a16c50f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.aarch64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "4b8d622b3b6c62a7ae48ed0d5740ca57fe54a8e2"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "986e4b0c266f0ea3dd5b26976f830b5b52d3b52b0b49d4dfcbb9d4ef4a747037"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.aarch64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0ffd65a29a25d1d0508d305890c4f9190a9da917"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "a24b85478f9593ff4197fac1332b64f6a8a1adb5e28781220a4da1b524dcbdb0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3830df76f8b06e8f6004eb33739a5a0acaa0d67a"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "f5ec3d339a57b87db9a04c68e26d10e7f55bd157dedf28674a0a149cf037304d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.armv6l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e684644d0e6864276815067d4ce5093b5f842ec3"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "91a339f06fb994181a3d3bec2a037e87dd6cc9500891ebcd989717ee58cc6c9e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1f56373b1f683b3b809b6d431d21f9d550c92d49"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "68b08d49cbc60abd300ff172d66baeff58a26020dbe3841c33a9989b1dbd2847"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.armv7l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "f7ebc1d5ed2246b0a49ec31359ac914c9ca33840"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "dcb0330c38fa628951b703a8e322180dbfe7c8a39971d9165415624759bc7532"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.i686-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "bf03566ec9e4708fa8c2c00a672f4a3c8411d1eb"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "6f39020cc635f941c076bf221aedc5c720a7284631ac265d295fc84fd9de95ed"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.i686-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "powerpc64le"
git-tree-sha1 = "a0265e47a358940a79cef4494a6a821ce4e126cb"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "5b3c3f4ec36540e353990483b7e619d32809d2a1bb294adb476e36b003d3d1f0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.powerpc64le-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "riscv64"
git-tree-sha1 = "51102d9eeea22378e63c5b2c31a608e9ed4b57db"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "2d7e6482d983730164598a0075fd75c16cac82d778456ae41009377be0a58ca8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.riscv64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "efdf985c13e879b5b9c9b24f058c13f4d391da20"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "96448300ddee58e62f7dd2f2903fdc432616c2698ce560613d8eda33a2d612e8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.x86_64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "ad180b9fbaacae8469a9d572f7a935f633efbdc8"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "8dbe20a86173e029d1b1e161f5d0b09a138a34ad10addf5f6e1d0bc005fe2747"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.x86_64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "c102091627f1fa8e0c6a183561ed884a49489849"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "443942829e37a79403657f662b5da1ee9823bc293d238952716091158a218df5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.x86_64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "934fccefce54374491274881901ffaedf352abff"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "99152ccf6be4cd036d488c0916d6f2fbe0d741151430e57a3ed604803149b570"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.x86_64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "861fb1f7008a81cc8cfa1c3b961f1f4b5d0e3165"
os = "windows"

    [[aws_c_s3.download]]
    sha256 = "76a771a333f4555a5a7448aaf767bdf423891c75261c9094f3ed0b933a727433"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.9.3+0/aws_c_s3.v0.9.3.x86_64-w64-mingw32.tar.gz"
