[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "f534e10b55be4e6aa19848142d0decbaad457354"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "16bbfbde4382f17eeaceab1cbab4de0ca3f645fc5a89f793d893706a937ef950"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.aarch64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "16a234007bd7aea3b68bbcd8a76b37e15058252b"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "7728f39d49fa15272a2bb0c12f49d530a981c7826167bacdbebdf7c20481f7bf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.aarch64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "86618510351ce4c820ea8dc99f1c935ef210d073"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "6fccca563d606a059c0ebe12410b9e39a455a7dc43126fbd6a9c03bce560e65f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.aarch64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "094442a4fc9e40f917e5a26b95468f32f9a98c95"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "fe1dc1474511d9ae1536b1df5f709293ad720873eae95ac1d952064168a028e1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.aarch64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6f01e4d021d998b6beacd4cc2905ce7ac65a90ff"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "9b97329bcb269691c3dfc346cd886025c8fa14fc7a7107b8468868cbdaf1518e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d90df89ede800099e3c507f02b597c0612502a5f"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "5fc3d671279fe4b7d827e66c9737b171388d99685a83d899241f73e896ad98bb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.armv6l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1afb3ea167566c7cc5936d696924acc3b9800b70"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "71186335c2adc156fc16472fca5b143d2936447702d8fc30e55674f0b1289a82"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ace3f98c4e1ce59bef6827e279ec11cdf9df2c20"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "45f4ecc9a2d6c13849bb466bbae21e631cf5c3bfd0abf445c0e909cbaef1c308"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.armv7l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "9e64852fbd54d58e0be4cfb8536894be5fa10745"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "181eccc8ccad1cbd01592f4e4dcae6a1db82e86e12c604728fc92db95e27d562"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.i686-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "28374a3aeefcdd70e5f52df0293dadb29b422512"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "adc82764ca70cf7eafdaf36a5470735babe63aba1140506a5bd7778cf21c1863"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.i686-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "powerpc64le"
git-tree-sha1 = "84eb90f60939c410b4e659d4344c7c979235ec25"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "cde71028250f53ae6b862720d9152de02fcfa9fb2a172fa3364f9150458b2ff7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.powerpc64le-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "riscv64"
git-tree-sha1 = "e397b8616ead7e26c0394111fd5cbbf69498ec2b"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "b497cecc33e285f507020873eaf64c4c94a3a85f16ad178183f4f7a1ce9f5341"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.riscv64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "ef4becb99f74fcb49db3f67b940366404faffb23"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "f32843be906ff8608ec0cce3687cd65b068e656c4ebce30632596c6351eb69a9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.x86_64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "01f26b1817704936b15978736effb69179c6a734"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "0766576feecc6d8d4bf3e4b565081e69a484cdd85157120f848d461dd8b17c0f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.x86_64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "bdb575c96fcd36ce245c4ed4418f95a544c755e8"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "dd9fb2c2222bb1e8edede17182365a01d2d745f45125defc7d9e1ea2de263e50"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.x86_64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "fff1412d4fb1837b15eeffe4c40d8adc7e821c78"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "62afdee7adb631e4299d430d59212b4b95ba81fa07709efce79c2d10841ac905"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.x86_64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "6deacac0ba8ee0c6fbe018dfdbd20862828eba5e"
os = "windows"

    [[aws_c_s3.download]]
    sha256 = "654e8bd92c7373614121649497084a78d9734d79dbf0973b1d5017e5ee37f8a9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.3+0/aws_c_s3.v0.11.3.x86_64-w64-mingw32.tar.gz"
