[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "ed6a3ac96b48ac9f874accb7e408e47ae3e1ee6b"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "b4916aae14431e17eaebfb06cabaff02ee18aecd0080992b07723fc2bebf6293"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.aarch64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "b695575840c0ab950514e912c69568bcbef4b9bc"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "0e845efae6c7a6bd83fbfb3165397c8c989caa69c819e9c7da79afead697dc12"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.aarch64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "10f856f89942db4eb12317d1363ba47f33255762"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "e6b3be5e927c9eec2f26274a479384e08d27bc85322b201147f78bb12c02fa81"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.aarch64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "27cba71ba9e00917435050e03832ca63c9091baa"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "b92718ceb381f91365030116b910cdf89152693cf7be9047f3c4db4037423f55"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.aarch64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76fb254668f56492486a1719ae422cc3655d0459"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "e97ec9ea7ee7c82dcaa0f9448e8b98ed5293604e8f10c1dd72c67b9c5fcbf276"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3f6673e1d8af8cbee32d5f2fa79c85e17ecee8c1"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "eedfae871f535b798f5dba01f6565686d484d2b705802ef36596c351d6e15fa9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.armv6l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5bb2f07df28f653683a3d24a086e1eab8417a987"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "d5c04dc1ec93b2080037cdb4e11652abdf44ec80301e880b9326e0e102eac4ef"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "719556f8b05796d86098ce286761921a2b595b49"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "6e8e28ffdeb54e274f90f40dd2269cb16870c7ed03b5ab6e19438d8d56651ac8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.armv7l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "2dd1ab799e712d212f3ae097c8d2335aaa9e4efb"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "f08f62dbc107a713cb7e2293b10f60cc9061960df267e36ee4aa49b1be0bb8bc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.i686-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "51277b4ed6f620aab5da504cd94f218fd9addcae"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "212fa6febc78f94e6ef5b34e9a85ca25ce0a880a202e8572e7cc74ba7cf7f84b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.i686-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "powerpc64le"
git-tree-sha1 = "3e885c812bc401d5c8b2d499929704db18ef2338"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "172fb2fbb1e78875f59162989d2334b06ff1dea842e5111f48720d7978764dc4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.powerpc64le-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "riscv64"
git-tree-sha1 = "9e72e27ece57c845cb1b7cc3a3b8a6c8ed2d6b1f"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "dd9c71603bb267260fa277b5256af07998dd0e6cdfc1374ca5b9724f987ca6cb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.riscv64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "cea4068211ba849f9098af39096815efe54d2638"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "615b20f921a7d76fd77398754d07250613fbb6c7a780199d9071508253eca00c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.x86_64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "c6539c99dec0fddacee6ab482e179df00108c66d"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "af7f3e43cd899465b492fd2b01a4e28453b5fcc55903d68dba87d47d1fdb989e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.x86_64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "4a75ae5914af908fc2f2d7a667b3373af630aef8"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "5b849bebc52db025bff0d4c3c14794ffea1c8a68760c4f5c3aaf1167691396f4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.x86_64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "313d1d523e824a0033444dcc59438029259a97f4"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "13d32ae9d56923852a3fa9157862527ec63880254cc993131e3c7e64e22f196b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.x86_64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "4212dc73b4e8f151bf07d4e906fcd3b2ba6a7965"
os = "windows"

    [[aws_c_s3.download]]
    sha256 = "35d4dd7c32847ea20e9910d474b176f1e7ad27f10f379b1590a0ee381ab597e1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.5+0/aws_c_s3.v0.11.5.x86_64-w64-mingw32.tar.gz"
