[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "304e0f7f6910dcfc1a440a8cca93af0e140e216d"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "765a845fbe5cf3e8d8f64e906e9229d20f7b706e757bcc2cdf4aea2110015c21"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.aarch64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "e4123a2e9597c399a4b3c538165723c0f2f46d49"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "2735607405ddc5b7c08af1e4056f1b4ffb6a7ca7b8b4995b7efee0d68c77b904"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.aarch64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "0bc03521bd3c3b50d46fe1e5208736214464abb9"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "efc01d6aab9b6c069fb181d3ef540afa5d8afe69c401b13930f89ae310732fc3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.aarch64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "5560c97da258f4ff6b1fb1d7974aa125e108acf6"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "8b6f04dd1f7a2c1ff481d032e23a7690e36fd9d31716902c00e01c5404ce1e15"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.aarch64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "264b772a33a42ed4633107a8e9bcb7bd5d95b522"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "26d640a5619593ed42b699aa82abf0ad77bbe85c80fdcc6084948dc1478b06a2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "210ea6123c884022298c05b7c4f4250c169ce096"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "039d430ccef26bb9dc3b57556af0a60fe8a9efaa166e1c79211537e6dfd9008d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.armv6l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "377be4fbabcfd3cbb0547e17f7dfadff9dd10f03"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "c31270fc8410610e300b6536af9de615463cef87cd4c169f456271cebae3626e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce693bbc0af1022ab032598780a56624da8c0967"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "81dccf9db6db872f139e4c2cb7d0817fe9909bc2433f2854a9b65895e96f7120"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.armv7l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "f4500fe0178b3213f888f16ed700a1bf1b4a06de"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "939bae0109ebb883ca043a1dbf3eac9736868284285d636ea0a312d740641d19"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.i686-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "d924d6c78cc08bbd3131321638df2726d96dea7e"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "195b45da8a0b83a7e31c594570fd23e949767f18ab0b1967ecb853faa9c8ef74"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.i686-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "powerpc64le"
git-tree-sha1 = "d06df9239cde0c5dac4e4881850d975d5c94cff1"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "9d269f06be66dc7b70f7572f295239416d6b8bb0319c711cb1740e935d4ee9dd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.powerpc64le-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "riscv64"
git-tree-sha1 = "54328380c0c4daa6207ba75cafd993c117f2fd81"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "2d407df15d3e1cefe680fc2c93cc917cf3b94b2fcb85db4fac187a2e10e81de3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.riscv64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "ed6e6b5fdeedcf9a55bd5b5aa6215559a341bfb8"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "de8ed2a7dccc9753d5730e435b48515c2f32bf8a06dc6dd2443667b1fca53e4f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.x86_64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "e1ac13613252fe6a78f1223496add4c7e4db7dfb"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "0d938dcab41632c8f3226bc2fe7854bccac24267369dbf51591ce57880766864"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.x86_64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "d1f47a2ace1c72f6603c77e1c7f51f4cacaeb74b"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "c50e5977bc480b82a84d832976d0749920ced3c5ca06ce15b70eb2f7ef7bfcd2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.x86_64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "b611b23394a8c306f920e54911ed9d1691d4d088"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "86332f336d2d7a618e54fa9bbefec154563fc13fcc4d6d826e8096ea835e1b67"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.x86_64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "76b356445ca729aa7c27524f18e8c0a5e300aca8"
os = "windows"

    [[aws_c_s3.download]]
    sha256 = "ba5b8db9049a6adf7695531260a74beb491759aff3d66d424e71cb8e7c584eac"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.0+0/aws_c_s3.v0.11.0.x86_64-w64-mingw32.tar.gz"
