[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "6342e9748f5ec65c5b593ec5abd1cd2b17daaf6b"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "cf53c113a966f06f6a8a128b0c3ff350eda51668b1ee1b84eea364e90096f364"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.aarch64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "095000fe02c4cd2ad2ddefb38f1df0a0a5e607c7"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "aecd949fd22a7e180ca78e9535095d777e0f1e649dffc72bcddba06219c38240"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.aarch64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "fd6d6e377d2faa8b3c13269fff23f2f8a89038ad"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "a2f7ed75a42d2dcf2cd4cef805251296d247ee1c082a81e4b07239759c4e5342"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.aarch64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "c0905b515016328c175392475b130d14af9331b9"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "0cff3253a009d1de9df87193170a3118d5e658d4ac1ac2f19de8513f325d7155"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.aarch64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "289efad7a51fd496f39fd73e8a9d78d338a7a74f"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "cfac901a1fdc04a84fd0897f3ef6551f93d834b778b18bcaf2e564d9ba0b4303"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e3303f2afba5cc4d91f56c34fc3c86759b0f57c6"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "b807191881dcef4912b777e888df2eab10112f133ca044e4a3e40377581fadd2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.armv6l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6240952085e8f4a6e8e38da42136187e9ed5b4de"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "aa39c7a8d7df3f543790f9cdf8eadaf6d344e91dad1be99b477f7a6fff614a1d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3595dc7949a53344713a3e6b82244a1a8ce50ee1"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "0bbd3a9872c353ff1081af66fca1ef85615c4b9fb20a1c4c819d34384616f75b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.armv7l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "269e8501bb5ecce239a96771af6ddd17582c5215"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "d25aeb5786a74dc06711d8d52dc93140b2d937cad0a92ac45523b2f8c6e6d202"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.i686-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "06b2fa2229e6acee84f831a3dafef6d40b8e87bb"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "679a00b3dc08d2e021e6f0f884bf258a5c3b646128c882580f0a5c0a35668d97"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.i686-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "powerpc64le"
git-tree-sha1 = "f7608d6cf4e6ed7718c559f305afd47a686ec972"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "a8fbf35201a3b157f714c2081813248a7e525bd97c9a6b2034e2f1f1829a2198"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.powerpc64le-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "riscv64"
git-tree-sha1 = "e903e3c1d1e790bc1fcdcef267b0517cef59072e"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "1354195472cd0832ac2f98a0f330fd25989fffeaf2f509d03a43b654fc937fa5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.riscv64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "958624d7f505750c784fa5e712af820e7ed53f2d"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "3ecf26b0ce20025f1a9cc5a84fd7005b36d7577ae44108ac454d4d7f5344d7d4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.x86_64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "55d1bc56707afd518a0e614e28d76fa277692ecd"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "8b606aa59ffe34d31a77ca59c6eb6740036ba60c5de29ef391a8ef165a871b5a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.x86_64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "d1bc8fada88eba447ee47652fd40ac2c4c284e67"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "d9127f65e0d59031573f5a74a261a295fa78cdbb153f395e53c31ff091c553d9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.x86_64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "386839bd714542abc2367fba456bd7dffcd8172d"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "3e846ed8f29307039867b6b247ca8aeea6874e01a54c2e317f89627ac517f760"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.x86_64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "16faa559198fe5099f48672cd53ade3e8e0dca25"
os = "windows"

    [[aws_c_s3.download]]
    sha256 = "6cc89b5e1633a0c6d0bdac3f2ad0ace6c6ee8922060f037382033d631a892e07"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.11.4+0/aws_c_s3.v0.11.4.x86_64-w64-mingw32.tar.gz"
