[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "3645aa5fb80485d1714cf7064c6b508bf3dc148f"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "08f650d43c6616a8a41b17faab21d8a3ea7f3f6995f2fa9ab5d94e5e9767f13b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.aarch64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "2a5937149b4fafb554909842759690a48c9aa202"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "326fd405181715463fd9250eb41b22904843a3a7661e740e62bdb8d9dba1bdf9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.aarch64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "ec74fcb006449624d1082c3ef757bcf0a562e37d"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "0992ea1bae4a5fa3c007e5c42437bb8bb80b19fb2b8fcbccf70ae255536e6ab8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.aarch64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "4661d0ed972bb334bbe2f4020472b3d2dd6312ab"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "df8df145b3c02491df4606d30b9d783e66bdd557c5738e9586120b5e59af393c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.aarch64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9d8daddae7b3fafaf8e98dce03a0067b009ed3b2"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "182489520a498396b9783bcd4ef6658759f8e805c3febbed8ab00464caa8e653"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c5091e248558bcba633e22757da2c505d6ae3808"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "f6d03de83d5f0cd55d9ce642cb9ad2c40f902ffefbab7739ab3b26b782c97a41"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.armv6l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "639f6636d05a6ddb490fc49f6dc66a3ec598f98d"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "e0e624adcae51fa25aaf7bf134599da914104b8ad99b7652696a80e0b105826b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "85affbe5c5bdffbbf4b0e07c7f253fc1b4a3666c"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "4c95c9f7fcc1fafec4ba23ab2ff1ea017ff428056a0bf6b27b494c690b3f26ee"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.armv7l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "210ad8ba8837d5a1340bc6e4ebdf45b2edf26552"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "5ce88af435b23cf66edb35457191c5ce248684e0ee000347ad8214781b07e7f6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.i686-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "71b589cf763b8d4c61c50ea2d04fd519a2df7f9d"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "dcd87cb37d8239e2f658bdc5472cf754f3619113a31bd4be7e7de951440c14ae"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.i686-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "powerpc64le"
git-tree-sha1 = "36723c66c0ced5c79d01ff49086b0c79fd50ba2a"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "aab7e4559b1c7553c210cf22dac5d570c6e7fbc778cc2ecb65e312316bec79e5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.powerpc64le-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "riscv64"
git-tree-sha1 = "df86706df345dd865165759171284edf01b18f62"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "b1ba4b38d5a3804a8f1f0c38d6905da4e8b2b48a49aeaa4b13b11f7690457a0f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.riscv64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "0897a69bd80bcbbbbda115c78af918d88d2b6e0a"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "003ce53b67cfb7017f5de17c737230cebc7a3ee5d37be4cde12c20ddbacdf8c0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.x86_64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "ffc9b0c7650197dcd37d0f1f0ea19d25cdd70988"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "f1686db5a8f506a6903ff5fd8f60db4a458bfe70b50783ce8b77f012e55bc5b0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.x86_64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "07779de56a010b8e7f87fd6d51d79f7245efd076"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "69ab5e015975e90c1cdc080e238a6b6c4a4ba702284e8ceece740e69d6c64b36"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.x86_64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "03e4369c114976a0e470e2ee0840bb9f5f05d9e1"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "ae293c860efc3b4b3a94a2b8e5cda4990f64150e6751f7dd0988955cb57f67c0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.x86_64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "eb8fbb71ab8df08faac9f4100b04f36a6bb41f90"
os = "windows"

    [[aws_c_s3.download]]
    sha256 = "0b920947bf751a95e33048aad4eb07a883cccb3e7a43b040a91e5c506d22e62c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v0.10.1+0/aws_c_s3.v0.10.1.x86_64-w64-mingw32.tar.gz"
