name = "aws_c_s3_jll"
uuid = "bd1f34fb-993f-5903-a121-aaf302eed6d4"
version = "0.10.1+0"

[deps]
aws_c_http_jll = "3254fc65-9028-534d-aa9d-d76d128babc6"
s2n_tls_jll = "cddc5d3d-934d-5d3a-9747-62fc12ea3f48"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
aws_checksums_jll = "b2a88e68-78e7-5e94-8c20-c02986ec140e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
aws_c_common_jll = "73048d1d-b8c4-5092-a58d-866c5e8d1e50"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
aws_c_auth_jll = "2b3700d1-4306-52e2-a478-c162f0c514be"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
aws_c_http_jll = "0.10.7"
s2n_tls_jll = "1.6.0"
aws_checksums_jll = "0.2.8"
Libdl = "< 0.0.1, 1"
aws_c_common_jll = "0.12.6"
Artifacts = "< 0.0.1, 1"
aws_c_auth_jll = "0.9.2"
